### ISSUE TITLE
startup bombs if no plugin configuration files (ST or Atom) can be found

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/mavensmate-app#1]
```
Error: ENOENT: no such file or directory, scandir ''
   at Error (native)
   at Object.fs.readdirSync (fs.js:813:18)
   at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:449:28)
   at MavensMateUtil.listDirectories (/home/josephferraro/Desktop/mavensmate-app/resources/app/node_modules/mavensmate/lib/mavensmate/util.js:155:21)
   at /home/josephferraro/Desktop/mavensmate-app/resources/app/node_modules/mavensmate/lib/mavensmate/ui/helper.js:37:29
   at Function.forEach (/home/josephferraro/Desktop/mavensmate-app/resources/app/node_modules/lodash/dist/lodash.js:3297:15)
   at ViewHelper.listProjects (/home/josephferraro/Desktop/mavensmate-app/resources/app/node_modules/mavensmate/lib/mavensmate/ui/helper.js:36:5)
   at evalmachine.<anonymous>:175:1521
   at Object.tpl (evalmachine.<anonymous>:196:3)
   at compiled (/home/josephferraro/Desktop/mavensmate-app/resources/app/node_modules/swig/lib/swig.js:658:18)
   at /home/josephferraro/Desktop/mavensmate-app/resources/app/node_modules/swig/lib/swig.js:598:20
   at /home/josephferraro/Desktop/mavensmate-app/resources/app/node_modules/swig/lib/swig.js:729:9
   at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by joeferraro** [comment]
mavensmate no longer requires client-specific config files
