### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by jeancdc** [joeferraro/MavensMate-app#122]
Hi,

Since this day, I've got this problem when I open MavensMate app:

```
Uncaught Exception:
Error: listen EADDRINUSE :::56248
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at Server._listen2 (net.js:1214:14)
    at listen (net.js:1250:10)
    at Server.listen (net.js:1340:5)
    at UIServer.startServer (/opt/MavensMate-atom/resources/app/node_modules/mavensmate/lib/mavensmate/ui/server.js:333:19)
    at /opt/MavensMate-atom/resources/app/node_modules/mavensmate/lib/mavensmate/ui/server.js:41:12
    at tryCatch2 (/opt/MavensMate-atom/resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/opt/MavensMate-atom/resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/opt/MavensMate-atom/resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at UIServer.start (/opt/MavensMate-atom/resources/app/node_modules/mavensmate/lib/mavensmate/ui/server.js:38:10)
    at /opt/MavensMate-atom/resources/app/node_modules/mavensmate/lib/mavensmate.js:25:12
    at tryCatch2 (/opt/MavensMate-atom/resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/opt/MavensMate-atom/resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/opt/MavensMate-atom/resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at Object.mavensmate.startServer (/opt/MavensMate-atom/resources/app/node_modules/mavensmate/lib/mavensmate.js:11:10)
```

**Comment by jeancdc** [comment]
I don't have this error anymore. I don't know what happened.
