### ISSUE TITLE
Response Error / Server crash when running edit project command

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/mavensmate-app#16]
version: v0.0.1-rc2

### Steps to reproduce
- open mavensmate app
- open st3
- open mm project 
- launch edit project command from command palette

### Excepted Outcome
edit project dialog launches

### Actual Outcome
first time the command is run getting an error in st3 
```                                                                       
Operation: Opening Edit Project dialog
Timestamp: Thu, 10 Sep 2015 12:18:01
   Result: [ERROR]: Request to the local MavensMate server failed. No JSON object could be decoded
```

second time, new tab opens but just shows the following error
```
TypeError: Cannot read property 'metadataObjects' of undefined
   at ViewHelper.getMetadataObjects (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/ui/helper.js:84:40)
   at evalmachine.<anonymous>:266:1617
   at Object.tpl (evalmachine.<anonymous>:299:3)
   at compiled (/Applications/MavensMate.app/Contents/Resources/app/node_modules/swig/lib/swig.js:658:18)
   at /Applications/MavensMate.app/Contents/Resources/app/node_modules/swig/lib/swig.js:598:20
   at /Applications/MavensMate.app/Contents/Resources/app/node_modules/swig/lib/swig.js:729:9
   at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

### Logs
added to a gist: https://gist.github.com/ralphcallaway/7f99b72843982df58bed

**Comment by ralphcallaway** [comment]
this one is a bit confusing, i've tried install rc1, beta9, beta8 and I'm still getting the error, but I'm nearly positive I'd done this with beta9 without getting this error

maybe this is related to the st3 beta5 version? not sure how, but the timing seems correct

**Comment by ralphcallaway** [comment]
so was able to get this working with rc2 after wiping out the config folder in the project and creating a new mm project

not sure if it could be related, but the org had an expired password, so it could be there was an error making a call with the existing credentials

tried this with a couple other projects and it seems to be working fine ... not having any luck reproducing after recreating that project ...

**Comment by ralphcallaway** [comment]
closing this since it seems like a one off and i can't reproduce 

@joeferraro re-open if this is something you think you need to look into
