### ISSUE TITLE
Invalid_Session_Id error with new MM v0.0.3

### ISSUE THREAD

**Issue by tglaess** [joeferraro/MavensMate-app#22]
I downloaded the new v0.0.3 this morning and now when I try to compile anything I get this error. Is there something I need to do?

Result: [ERROR]: Request to the local MavensMate server failed. Error initializing project: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session key: 00DZ000000BbePo!AR8AQFxKgPNmo.1gSWIWMILh94vulkoKSOKbHFCOrcnH.POQedlTu2bTK7SqzbglAlnImqwqgXmUIuURxt.71yDb47FqN5bY
This is expected, it can happen if the session has expired and swept away, or if the user logs out, or if its just someone trying to hack in.

**Comment by joeferraro** [comment]
Hi @tglaess thanks for the bug report. Can you please provide your platform and specific steps to reproduce?

**Comment by joeferraro** [comment]
Also, can you go to Settings and set your log level to `SILLY`, the log location to a location on your drive, and paste any relevant logs?

**Comment by tglaess** [comment]
I'm on OS X. I downloaded the v0.0.3 version of the app and it seems to be running fine. In Sublime Text, I edited some APEX code and compiled it. That's when I get the above error.
I also get the error when I try to open my MM project in the App.
I am running the v5.0.0-beta-2 version of MM for Sublime Text. Should I upgrade that?

**Comment by joeferraro** [comment]
Definitely update to v5.0.0 of the plugin and retry.

**Comment by joeferraro** [comment]
Also, I imagine as a temporary workaround, restarting MavensMate-app should fix this issue, as that will force any projects to obtain a valid access token.

**Comment by tglaess** [comment]
I upgraded the plugin and restarted both the app and sublime. I still get the error. I will get the logs and attach them.

**Comment by tglaess** [comment]
unfortunately, when I try to start logging, I get the same session ID error.

**Comment by joeferraro** [comment]
To set up MavensMate logs, you need to go to MavensMate-app, go to Settings, and set your levels/location. Once those are set up, restart MavensMate-app and run your compilation in Sublime Text. This will produce a log called mavensmate.log that you should paste to this issue.

**Comment by tglaess** [comment]
Ok, here you go:

2015-09-29T17:12:31.408Z - debug: Processing request GET for URL: /app/settings/index
2015-09-29T17:12:31.744Z - debug: query params v=3.1.0
2015-09-29T17:13:01.676Z - debug: Processing request POST for URL: /app/settings/update
2015-09-29T17:13:01.677Z - debug: post body settingValue=SILLY, settingKey=mm_log_level
2015-09-29T17:13:24.351Z - info: initiated client:  {"name":"mavensmate-app","isServer":true,"isNodeApp":false,"isCommandLine":false,"settings":{"type":"literal"}}
2015-09-29T17:13:24.775Z - debug: Processing request GET for URL: /app/home/index
2015-09-29T17:13:24.838Z - silly: Processing request GET for URL: /app/static/bootstrap/css/bootstrap.css
2015-09-29T17:13:24.842Z - silly: Processing request GET for URL: /app/static/bootstrap/css/bootstrap-responsive.css
2015-09-29T17:13:24.843Z - silly: Processing request GET for URL: /app/static/css/flat-ui.css
2015-09-29T17:13:24.845Z - silly: Processing request GET for URL: /app/static/css/mavensmate.css
2015-09-29T17:13:24.847Z - silly: Processing request GET for URL: /app/static/css/prettify.css
2015-09-29T17:13:24.848Z - silly: Processing request GET for URL: /app/static/css/dynatree.css
2015-09-29T17:13:24.848Z - silly: Processing request GET for URL: /app/static/css/font-awesome.min.css
2015-09-29T17:13:24.850Z - silly: Processing request GET for URL: /app/static/js/jqueryui.js
2015-09-29T17:13:24.850Z - silly: Processing request GET for URL: /app/static/js/bootstrap.min.js
2015-09-29T17:13:24.851Z - silly: Processing request GET for URL: /app/static/js/bootstrap-select.js
2015-09-29T17:13:24.852Z - silly: Processing request GET for URL: /app/static/js/flatui-checkbox.js
2015-09-29T17:13:24.852Z - silly: Processing request GET for URL: /app/static/js/jquery.js
2015-09-29T17:13:24.853Z - silly: Processing request GET for URL: /app/static/js/mavensmate.js
2015-09-29T17:13:24.855Z - silly: Processing request GET for URL: /app/static/js/dynatree2.js
2015-09-29T17:13:24.857Z - silly: Processing request GET for URL: /app/static/js/jquery.contextMenu-custom.js
2015-09-29T17:13:24.857Z - silly: Processing request GET for URL: /app/static/js/prettify.js
2015-09-29T17:13:24.860Z - silly: Processing request GET for URL: /app/static/images/burger.png
2015-09-29T17:13:24.863Z - silly: Processing request GET for URL: /app/static/images/open-project.png
2015-09-29T17:13:24.863Z - silly: Processing request GET for URL: /app/static/images/logo2.png
2015-09-29T17:13:30.620Z - debug: Processing request GET for URL: /app/home/index
2015-09-29T17:13:34.803Z - debug: Processing request POST for URL: /execute?command=compile-metadata&async=1&pid=EJNOI6MDNGM9OSJRFK3WR80JXNQMA2YR
2015-09-29T17:13:34.803Z - debug: post body paths=[/Users/tglaess/mm_workspace/BusinessSystemsSalesforce/src/classes/MergeCaseController.cls]
2015-09-29T17:13:34.804Z - debug: _findProjectPathById
2015-09-29T17:13:34.804Z - debug: EJNOI6MDNGM9OSJRFK3WR80JXNQMA2YR
2015-09-29T17:13:34.804Z - debug:  0=/Users/tglaess/mm_workspace
2015-09-29T17:13:34.804Z - debug: /Users/tglaess/mm_workspace
2015-09-29T17:13:34.804Z - debug:  0=/Users/tglaess/mm_workspace/BusinessSystemsSalesforce
2015-09-29T17:13:34.805Z - info: adding project by id ---->  EJNOI6MDNGM9OSJRFK3WR80JXNQMA2YR
2015-09-29T17:13:34.805Z - info: path:  /Users/tglaess/mm_workspace/BusinessSystemsSalesforce
2015-09-29T17:13:34.805Z - debug: initing existing project ...
2015-09-29T17:13:34.806Z - debug: initing package instance
2015-09-29T17:13:34.807Z - debug: deserializing: /Users/tglaess/mm_workspace/BusinessSystemsSalesforce/src/package.xml
2015-09-29T17:13:34.826Z - debug: parsed package.xml to -->{"ApexClass":"*","ApexComponent":"*","ApexPage":"*","ApexTrigger":"*","AuraDefinitionBundle":["Assign_Sales_Rep_Tool","svgIcon"],"CustomField":["Bug__c.Bug_Name__c","Bug__c.Description__c","Bug__c.Enhancement__c","Bug__c.Estimate_Hours_to_Fix__c","Bug__c.Resolution__c","Bug__c.Scope_Compliance__c","Bug__c.Severity__c","Bug__c.Status__c","Bug__c.Steps_to_Reproduce__c","Bug__c.Type__c"],"CustomObject":["Account","AccountContactRole","Activity","AircraftClass__c","AircraftCountry__c","AircraftCreators__c","Aircraft_Contact__c","Aircraft__c","Asset","Billing_Shipping_Address__c","Campaign","CampaignMember","Case","CaseContactRole","Case_Equipment__c","Contact","ContentVersion","Contract","ContractContactRole","Credit_Request_Item__c","Disable_Account_Change_Validation_Rule__c","Event","Idea","KeyValueStore__c","Lead","Opportunity","OpportunityCompetitor","OpportunityContactRole","OpportunityLineItem","OpportunityTeamMember","PartnerRole","Pricebook2","PricebookEntry","Product2","Service__c","Site","SocialPersona","Solution","StateMap__c","System__c","Task","Territory2","Territory2Model","User","UserTerritory2Association"],"Layout":"*","Profile":"*","StaticResource":"*","Workflow":["Account","AircraftClass__c","AircraftCountry__c","AircraftCreators__c","Aircraft_Contact__c","Aircraft__c","Asset","Billing_Shipping_Address__c","Campaign","CampaignMember","Case","Case_Equipment__c","Contact","Contract","Credit_Request_Item__c","Disable_Account_Change_Validation_Rule__c","EmailMessage","Event","Idea","KeyValueStore__c","Lead","Opportunity","OpportunityLineItem","OpportunityTeamMember","Organization","Product2","Service__c","Site","SocialPersona","Solution","StateMap__c","System__c","Task","User","UserLicense"]}
2015-09-29T17:13:34.827Z - debug: setting package subscription: 
2015-09-29T17:13:34.827Z - debug:  ApexClass=*, ApexComponent=*, ApexPage=*, ApexTrigger=*, AuraDefinitionBundle=[Assign_Sales_Rep_Tool, svgIcon], CustomField=[Bug__c.Bug_Name__c, Bug__c.Description__c, Bug__c.Enhancement__c, Bug__c.Estimate_Hours_to_Fix__c, Bug__c.Resolution__c, Bug__c.Scope_Compliance__c, Bug__c.Severity__c, Bug__c.Status__c, Bug__c.Steps_to_Reproduce__c, Bug__c.Type__c], CustomObject=[Account, AccountContactRole, Activity, AircraftClass__c, AircraftCountry__c, AircraftCreators__c, Aircraft_Contact__c, Aircraft__c, Asset, Billing_Shipping_Address__c, Campaign, CampaignMember, Case, CaseContactRole, Case_Equipment__c, Contact, ContentVersion, Contract, ContractContactRole, Credit_Request_Item__c, Disable_Account_Change_Validation_Rule__c, Event, Idea, KeyValueStore__c, Lead, Opportunity, OpportunityCompetitor, OpportunityContactRole, OpportunityLineItem, OpportunityTeamMember, PartnerRole, Pricebook2, PricebookEntry, Product2, Service__c, Site, SocialPersona, Solution, StateMap__c, System__c, Task, Territory2, Territory2Model, User, UserTerritory2Association], Layout=*, Profile=*, StaticResource=*, Workflow=[Account, AircraftClass__c, AircraftCountry__c, AircraftCreators__c, Aircraft_Contact__c, Aircraft__c, Asset, Billing_Shipping_Address__c, Campaign, CampaignMember, Case, Case_Equipment__c, Contact, Contract, Credit_Request_Item__c, Disable_Account_Change_Validation_Rule__c, EmailMessage, Event, Idea, KeyValueStore__c, Lead, Opportunity, OpportunityLineItem, OpportunityTeamMember, Organization, Product2, Service__c, Site, SocialPersona, Solution, StateMap__c, System__c, Task, User, UserLicense]
2015-09-29T17:13:34.839Z - debug: initiating SalesforceClient: 
2015-09-29T17:13:34.839Z - debug: initializing connection to salesforce ...
2015-09-29T17:13:34.881Z - debug: configuring jsforce ...
2015-09-29T17:13:35.691Z - error: Could not initiate existing Project instance: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session key: 00DZ000000BbePo!AR8AQFxKgPNmo.1gSWIWMILh94vulkoKSOKbHFCOrcnH.POQedlTu2bTK7SqzbglAlnImqwqgXmUIuURxt.71yDb47FqN5bY
This is expected, it can happen if the session has expired and swept away, or if the user logs out, or if its just someone trying to hack in. 
2015-09-29T17:13:35.692Z - error: Error initializing project: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session key: 00DZ000000BbePo!AR8AQFxKgPNmo.1gSWIWMILh94vulkoKSOKbHFCOrcnH.POQedlTu2bTK7SqzbglAlnImqwqgXmUIuURxt.71yDb47FqN5bY
This is expected, it can happen if the session has expired and swept away, or if the user logs out, or if its just someone trying to hack in.  -> sf:INVALID_SESSION_ID: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session key: 00DZ000000BbePo!AR8AQFxKgPNmo.1gSWIWMILh94vulkoKSOKbHFCOrcnH.POQedlTu2bTK7SqzbglAlnImqwqgXmUIuURxt.71yDb47FqN5bY
This is expected, it can happen if the session has expired and swept away, or if the user logs out, or if its just someone trying to hack in. 
    at HttpApi.getError (/Applications/MavensMate.app/Contents/Resources/app/node_modules/jsforce/lib/http-api.js:240:13)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/jsforce/lib/http-api.js:85:22
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/promise/lib/core.js:33:15
    at flush (/Applications/MavensMate.app/Contents/Resources/app/node_modules/asap/asap.js:27:13)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)

**Comment by joeferraro** [comment]
@tglaess apologies for the inconvenience, and thanks for helping me debug this. could you install this prerelease and let me know if it resolves your issue? https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.5

**Comment by tglaess** [comment]
Joe - thanks. That fixed it.

**Comment by niketsoral** [comment]
I am seeing the same issue on MAC.

**Comment by joeferraro** [comment]
@niketsoral what version of mavensmate-app are you running?
