### ISSUE TITLE
Error Locating Templates with VF Metadata Creation Dialog

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/mavensmate-app#5]
Using st3: v5.0.0-beta2, unknown app version (not sure what version since I can't find any version info in the app)

Steps to reproduce
- open mavensmate
- open project in ST3 
- execute new vf page command
- wait for mm app to load
- select template

Excepted Outcome
- no error

Actual Outcome
- get javascript error

Error Details
```
Uncaught Exception:
Error: ENOENT: no such file or directory, open 'joeferraro/MavensMate-Templates/master/ApexPage/HeaderPageBlock.page'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
    at MavensMateUtil.getFileBody (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/util.js:258:21)
    at Request._callback (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/template.js:48:31)
    at Request.self.callback (/Applications/MavensMate.app/Contents/Resources/app/node_modules/request/request.js:372:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Applications/MavensMate.app/Contents/Resources/app/node_modules/request/request.js:1310:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Applications/MavensMate.app/Contents/Resources/app/node_modules/request/request.js:1258:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

Side note, apparently I can't use apple-c to copy something with the error dialogs in the mm app (i have to right click and then select copy)

**Comment by ralphcallaway** [comment]
the following settings may apply
- mm_template_location: remote
- mm_template_source: joeferraro/MavensMate-Templates/master

**Comment by ralphcallaway** [comment]
this doesn't happen when creating apex page with default template

**Comment by ralphcallaway** [comment]
hmm, seems like it's working now ... maybe a momentary connection issue?

**Comment by dieffrei** [comment]
This issue started to happened to me now
