### ISSUE TITLE
 Resource bundle errors on creation (MM 7.0.0-beta.1)

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate-app#98]
Attempting to create a resource bundle on MM and getting the following error:

```
[MAVENSMATE]: Calling mavensmate adapter
[MAVENSMATE]: OPERATION: new-resource-bundle
[MAVENSMATE]: {'context': <MavensMate.mavensmate.CreateResourceBundleCommand object at 0x1064b3690>, 'body': {'paths': ['/Users/kyle/workspace/path/src/staticresources/MavensGlobalAssets.resource']}, 'message': 'Creating resource bundle...'}
[MAVENSMATE]: http://localhost:56248/execute?command=new-resource-bundle&async=1&pid=BAUVVUDBAI12JYORQMB9LIO03T4OELAG
[MAVENSMATE]: posting to MavensMate:
[MAVENSMATE]: b'{"paths": ["/Users/kyle/workspace/path/src/staticresources/MavensGlobalAssets.resource"]}'
[MAVENSMATE]: response from MavensMate
[MAVENSMATE]: <http.client.HTTPResponse object at 0x1049fb810>
[MAVENSMATE]: {'id': 'f5242ce0-78c4-11e5-9f1d-35868b3b9524', 'complete': True, 'stack': 'Error: Could not create resource bundle(s): Could not write bundle stream for /Users/kyle/workspace/path/src/staticresources/MavensGlobalAssets.resource: Could not extract and write stream to file system.\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/resource-bundle.js:54:16\n    at tryCatch1 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:45:21)\n    at Promise._callHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:571:13)\n    at Promise._settlePromiseFromHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:581:18)\n    at Promise._settlePromiseAt (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:733:18)\n    at Promise._settlePromises (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:845:14)\n    at Async._consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:85:12)\n    at Async.consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:40:14)\n    at doNTCallback0 (node.js:416:9)\n    at process._tickCallback (node.js:345:13)', 'error': 'Could not create resource bundle(s): Could not write bundle stream for /Users/kyle/workspace/path/src/staticresources/MavensGlobalAssets.resource: Could not extract and write stream to file system.', 'operation': 'new-resource-bundle'}
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'id': 'f5242ce0-78c4-11e5-9f1d-35868b3b9524', 'complete': True, 'stack': 'Error: Could not create resource bundle(s): Could not write bundle stream for /Users/kyle/workspace/path/src/staticresources/MavensGlobalAssets.resource: Could not extract and write stream to file system.\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/resource-bundle.js:54:16\n    at tryCatch1 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:45:21)\n    at Promise._callHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:571:13)\n    at Promise._settlePromiseFromHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:581:18)\n    at Promise._settlePromiseAt (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:733:18)\n    at Promise._settlePromises (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:845:14)\n    at Async._consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:85:12)\n    at Async.consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:40:14)\n    at doNTCallback0 (node.js:416:9)\n    at process._tickCallback (node.js:345:13)', 'error': 'Could not create resource bundle(s): Could not write bundle stream for /Users/kyle/workspace/client/src/staticresources/MavensGlobalAssets.resource: Could not extract and write stream to file system.', 'operation': 'new-resource-bundle'}
[MAVENSMATE] skipped community activity

```

**Comment by kylethornton** [comment]
Turns out the file was there already and the error is resulting from that. This is now more of an enhancement request than bug report.

**Comment by joeferraro** [comment]
so to be clear, this occurs when trying to create a resource bundle that already exists, correct?

**Comment by kylethornton** [comment]
Correct.

**Comment by joeferraro** [comment]
ok cool, actually tracking [here](https://github.com/joeferraro/MavensMate/issues/521), so will close this issue.

**Comment by kylethornton** [comment]
Apologies. I had searched and didn't see this issue.

**Comment by joeferraro** [comment]
no worries, different project
